tupla=('Estojo',9.99,'Lápis',0.99,'Borracha',2.00,'Caderno',5.00,'mochila',30.00)
print('            TABELA DE PREÇOS:')
print('  -------------------------------------')
print(' |Produto:',tupla[0],'  ...','Preço:',tupla[1],'R$ |')
print(' |Produto:',tupla[2],'   ...','Preço:',tupla[3],'R$ |')
print(' |Produto:',tupla[4],'...','Preço:',tupla[5],' R$ |')
print(' |Produto:',tupla[6],' ...','Preço:',tupla[7],' R$ |')
print(' |Produto:',tupla[8],' ...','Preço:',tupla[9],'R$ |')
print('  -------------------------------------')